// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdp6ih3nXYAKpAYa-urD9YLfyKL2uy6FQ',
    appId: '1:1038095714065:web:c06c6a6ff424036eaaaeb0',
    messagingSenderId: '1038095714065',
    projectId: 'ekal-db',
    authDomain: 'ekal-db.firebaseapp.com',
    storageBucket: 'ekal-db.appspot.com',
    measurementId: 'G-WZGJ59Y0Z8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCb4ZMLz3TBqUIgjWZLxMBvqogmPp2AI_M',
    appId: '1:1038095714065:android:f18a4f8f2aefd590aaaeb0',
    messagingSenderId: '1038095714065',
    projectId: 'ekal-db',
    storageBucket: 'ekal-db.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADdLtQ1K0l88pe9CxdCATvIrBzvfiUdVA',
    appId: '1:1038095714065:ios:aa82f79c319404b9aaaeb0',
    messagingSenderId: '1038095714065',
    projectId: 'ekal-db',
    storageBucket: 'ekal-db.appspot.com',
    iosClientId: '1038095714065-ggj3c8hmtb92vt0aktie8c7u85j6dvs7.apps.googleusercontent.com',
    iosBundleId: 'com.example.instructorApp',
  );
}